In [1]:
import numpy as np
import torch

In [2]:
#f=2*x
#f =w*x

In [4]:
X = np.array([1,2,3,4], dtype=np.float32)
Y= np.array([2,4,6,8], dtype=np.float32)
w = 0.0

In [10]:
def forward(x):
    return w*x
def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()

In [6]:
#MSE = 1/N(wx-y)^2
#dJ/dw = 2x*1/N(wx-y)

In [7]:
def gradient(x,y,y_predicted):
    return np.dot(2*x,y_predicted-y).mean()

In [11]:
"Prediction before training, f(5)" , forward(5) 

('Prediction before training, f(5)', 0.0)

In [13]:
learning_rate = 0.01
n_iters = 10
for epoch in range(n_iters):
    # prediction: forward pass
    y_pred = forward(X)
    l = loss(Y,y_pred)
    dw = gradient(X,Y,y_pred)

    #update w
    w -= learning_rate*dw
    if epoch % 1 == 0:
        print(f'epoch{epoch+1}:w = {w:.3f}, loss = {l:.8f}')

epoch1:w = 1.200, loss = 30.00000000
epoch2:w = 1.680, loss = 4.79999924
epoch3:w = 1.872, loss = 0.76800019
epoch4:w = 1.949, loss = 0.12288000
epoch5:w = 1.980, loss = 0.01966083
epoch6:w = 1.992, loss = 0.00314570
epoch7:w = 1.997, loss = 0.00050332
epoch8:w = 1.999, loss = 0.00008053
epoch9:w = 1.999, loss = 0.00001288
epoch10:w = 2.000, loss = 0.00000206


In [14]:
"Prediction aft training, f(5)" , forward(5) 

('Prediction aft training, f(5)', 9.998951458930968)

In [25]:
X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y= torch.tensor([2,4,6,8], dtype=torch.float32)
w = torch.tensor(0.0, requires_grad=True)
def forward(x):
    return w*x
def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()
# def gradient(x,y,y_predicted):
#     return np.dot(2*x,y_predicted-y).mean()

In [26]:
learning_rate = 0.01
n_iters = 100
for epoch in range(n_iters):
    # prediction: forward pass
    y_pred = forward(X)
    l = loss(Y,y_pred)
    #gradients = backward pass
    # dw = gradient(X,Y,y_pred)
    l.backward()
    #update w
    with torch.no_grad():
        w -= learning_rate*w.grad
        # print(w.grad)
    w.grad.zero_()
    if epoch % 10 == 0:
        print(f'epoch{epoch+1}:w = {w:.3f}, loss = {l:.8f}')

epoch1:w = 0.300, loss = 30.00000000
epoch11:w = 1.665, loss = 1.16278565
epoch21:w = 1.934, loss = 0.04506890
epoch31:w = 1.987, loss = 0.00174685
epoch41:w = 1.997, loss = 0.00006770
epoch51:w = 1.999, loss = 0.00000262
epoch61:w = 2.000, loss = 0.00000010
epoch71:w = 2.000, loss = 0.00000000
epoch81:w = 2.000, loss = 0.00000000
epoch91:w = 2.000, loss = 0.00000000


In [27]:

X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y= torch.tensor([2,4,6,8], dtype=torch.float32)
w = torch.tensor(0.0, requires_grad=True)

def forward(x):
    return w*x
def loss(y,y_predicted):
    return ((y-y_predicted)**2).mean()
learning_rate = 0.01
n_iters = 100
for epoch in range(n_iters):
    # prediction: forward pass
    y_pred = forward(X)
    l = loss(Y,y_pred)
    #gradients = backward pass
    # dw = gradient(X,Y,y_pred)
    l.backward()

    #update w
    with torch.no_grad():
        w -= learning_rate*w.grad
        # print(w.grad)
    w.grad.zero_()
    if epoch % 10 == 0:
        print(f'epoch{epoch+1}:w = {w:.3f}, loss = {l:.8f}')

epoch1:w = 0.300, loss = 30.00000000
epoch11:w = 1.665, loss = 1.16278565
epoch21:w = 1.934, loss = 0.04506890
epoch31:w = 1.987, loss = 0.00174685
epoch41:w = 1.997, loss = 0.00006770
epoch51:w = 1.999, loss = 0.00000262
epoch61:w = 2.000, loss = 0.00000010
epoch71:w = 2.000, loss = 0.00000000
epoch81:w = 2.000, loss = 0.00000000
epoch91:w = 2.000, loss = 0.00000000


In [28]:
import torch.nn as nn

In [30]:
X = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
Y= torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)
n_samples, n_features = X.shape
# w = torch.tensor(0.0, requires_grad=True)


In [41]:
X_test = torch.tensor([5],dtype=torch.float32)

In [50]:
input_size = n_features
output_size = n_features
model = nn.Linear(input_size,output_size)


# def forward(x):
#     return w*x
# def loss(y,y_predicted):
#     return ((y-y_predicted)**2).mean()
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

learning_rate = 0.001
n_iters = 100

print(f"Prediction bef training, f(5):{ model(X_test)}") 
for epoch in range(n_iters):
    # prediction: forward pass
    y_pred = model(X)
    l = loss(Y,y_pred)
    #gradients = backward pass
    # dw = gradient(X,Y,y_pred)
    l.backward()

    #update w
    # with torch.no_grad():
    #     w -= learning_rate*w.grad
        # print(w.grad)
    optimizer.step()
    optimizer.zero_grad()
    # w.grad.zero_()
    if epoch % 10 == 0:
        [w,b] = model.parameters()
        print(f'epoch{epoch+1}:w = {w}, loss = {l}')

Prediction bef training, f(5):tensor([4.8966], grad_fn=<ViewBackward0>)
epoch1:w = Parameter containing:
tensor([[0.8097]], requires_grad=True), loss = 6.195752143859863
epoch11:w = Parameter containing:
tensor([[0.9328]], requires_grad=True), loss = 4.489911079406738
epoch21:w = Parameter containing:
tensor([[1.0370]], requires_grad=True), loss = 3.271498680114746
epoch31:w = Parameter containing:
tensor([[1.1252]], requires_grad=True), loss = 2.4011244773864746
epoch41:w = Parameter containing:
tensor([[1.2000]], requires_grad=True), loss = 1.7792651653289795
epoch51:w = Parameter containing:
tensor([[1.2633]], requires_grad=True), loss = 1.3348537683486938
epoch61:w = Parameter containing:
tensor([[1.3170]], requires_grad=True), loss = 1.0171465873718262
epoch71:w = Parameter containing:
tensor([[1.3626]], requires_grad=True), loss = 0.7899114489555359
epoch81:w = Parameter containing:
tensor([[1.4013]], requires_grad=True), loss = 0.6272797584533691
epoch91:w = Parameter containing

In [49]:
"Prediction aft training, f(5)" , model(X_test)

('Prediction aft training, f(5)', tensor([10.0658], grad_fn=<ViewBackward0>))

In [51]:
input_size = n_features
output_size = n_features
model = nn.Linear(input_size,output_size)
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim) -> None:
        super(LinearRegression,self).__init__()
        # define layers
        self.lin = nn.Linear(input_dim, output_dim)
    def forward(self,x):
        return self.lin(x)
model = LinearRegression(input_size,output_size)

# def forward(x):
#     return w*x
# def loss(y,y_predicted):
#     return ((y-y_predicted)**2).mean()
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

learning_rate = 0.001
n_iters = 100

print(f"Prediction bef training, f(5):{ model(X_test)}") 
for epoch in range(n_iters):
    # prediction: forward pass
    y_pred = model(X)
    l = loss(Y,y_pred)
    #gradients = backward pass
    # dw = gradient(X,Y,y_pred)
    l.backward()

    #update w
    # with torch.no_grad():
    #     w -= learning_rate*w.grad
        # print(w.grad)
    optimizer.step()
    optimizer.zero_grad()
    # w.grad.zero_()
    if epoch % 10 == 0:
        [w,b] = model.parameters()
        print(f'epoch{epoch+1}:w = {w}, loss = {l}')

Prediction bef training, f(5):tensor([1.9818], grad_fn=<ViewBackward0>)
epoch1:w = Parameter containing:
tensor([[0.5710]], requires_grad=True), loss = 21.84415054321289
epoch11:w = Parameter containing:
tensor([[0.8041]], requires_grad=True), loss = 15.599699020385742
epoch21:w = Parameter containing:
tensor([[1.0010]], requires_grad=True), loss = 11.140969276428223
epoch31:w = Parameter containing:
tensor([[1.1674]], requires_grad=True), loss = 7.957293510437012
epoch41:w = Parameter containing:
tensor([[1.3079]], requires_grad=True), loss = 5.684046745300293
epoch51:w = Parameter containing:
tensor([[1.4267]], requires_grad=True), loss = 4.060870170593262
epoch61:w = Parameter containing:
tensor([[1.5270]], requires_grad=True), loss = 2.9018635749816895
epoch71:w = Parameter containing:
tensor([[1.6117]], requires_grad=True), loss = 2.0742859840393066
epoch81:w = Parameter containing:
tensor([[1.6832]], requires_grad=True), loss = 1.4833579063415527
epoch91:w = Parameter containing: