## Reference: https://www.learnpytorch.io

In [6]:
import torch
import numpy as np
import matplotlib.pyplot as plt


Tensors only have a single datatype like numpy
default is float 32

In [3]:
# !pip list


In [4]:
l = [[1,2,3,4,5],[6,7,8,9,10],[11,12]]


In [12]:
np_a = np.random.randint(-1,100,size=(3,4))

In [13]:
np_a

array([[36, 93, -1,  8],
       [14, 73, 47,  2],
       [48, 15, 80,  4]])

In [16]:
tensor = torch.randint(-1,100,(3,4))

In [17]:
tensor_2 = torch.zeros((2,2,2))

In [18]:
tensor_2

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [19]:
tensor_from_np = torch.from_numpy(np_a)

In [20]:
tensor_from_np

tensor([[36, 93, -1,  8],
        [14, 73, 47,  2],
        [48, 15, 80,  4]])

In [21]:
tensor_from_np.dtype

torch.int64

In [22]:
tensor_from_np2 = torch.tensor(np_a)

In [23]:
tensor_from_np2

tensor([[36, 93, -1,  8],
        [14, 73, 47,  2],
        [48, 15, 80,  4]])

In [24]:
t1 = torch.arange(10)

Reshape and View -basically the same

In [26]:
t1 = t1.reshape(2,5)

In [27]:
t2 = torch.arange(12)

In [28]:
t2 = t2.reshape(3,-1)

In [29]:
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [30]:
t3 = torch.arange(12)

In [31]:
t3=t3.view(-1,4)

In [32]:
t3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshape takes reference so if original tensor changes the reshaped tensor changes too

In [34]:
t4 = torch.zeros(12)

In [35]:
t4

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
t5 = t4.reshape(4,-1)

In [37]:
t4[1] = 100

In [38]:
t4

tensor([  0., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [39]:
t5

tensor([[  0., 100.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

Slicing

In [40]:
t5[:,1]

tensor([100.,   0.,   0.,   0.])

In [43]:
t5[:,1:2]

tensor([[100.],
        [  0.],
        [  0.],
        [  0.]])

https://pytorch.org/docs/stable/generated/torch.rand.html

In [44]:
t6 = torch.rand(10,10,10)

In [45]:
t6

tensor([[[0.7709, 0.3053, 0.9657, 0.4937, 0.7668, 0.4597, 0.7529, 0.6220,
          0.7480, 0.8897],
         [0.6122, 0.9804, 0.7047, 0.7644, 0.8618, 0.3993, 0.1745, 0.1752,
          0.5059, 0.8340],
         [0.6967, 0.1039, 0.0260, 0.4729, 0.1983, 0.8412, 0.5885, 0.6537,
          0.9087, 0.9763],
         [0.3663, 0.8816, 0.6170, 0.8943, 0.0633, 0.0214, 0.3516, 0.5609,
          0.1436, 0.1163],
         [0.7446, 0.3386, 0.3790, 0.8275, 0.8701, 0.8670, 0.6720, 0.4878,
          0.9742, 0.4543],
         [0.8943, 0.9418, 0.2255, 0.3442, 0.9044, 0.5692, 0.3312, 0.2842,
          0.1079, 0.0383],
         [0.5819, 0.9082, 0.8470, 0.4228, 0.0970, 0.6812, 0.6711, 0.4812,
          0.6950, 0.2941],
         [0.1856, 0.6386, 0.2075, 0.2989, 0.6916, 0.9859, 0.7057, 0.5176,
          0.4783, 0.5505],
         [0.1407, 0.1669, 0.7549, 0.0617, 0.7538, 0.1182, 0.0256, 0.8322,
          0.0987, 0.3002],
         [0.8268, 0.1345, 0.8223, 0.3104, 0.9211, 0.9436, 0.1400, 0.0080,
          0.7191,

In [46]:
t6.shape

torch.Size([10, 10, 10])

In [47]:
t6.ndim

3

shape and size are the same thing


In [49]:
t6.size()

torch.Size([10, 10, 10])

In [50]:
image = torch.rand(224,224,3)