In [44]:
import torch
import numpy as np

In [21]:
x = torch.rand(2,2)
y= torch.rand(2,2)

In [22]:
x,y

(tensor([[0.3238, 0.7311],
         [0.5166, 0.3750]]),
 tensor([[0.8832, 0.4588],
         [0.3521, 0.1240]]))

In [23]:
z = x+y

In [25]:
z = torch.add(x,y)

In [26]:
y.add_(x)

tensor([[1.2070, 1.1899],
        [0.8687, 0.4990]])

In [28]:
y.mul_(x)

tensor([[0.3908, 0.8700],
        [0.4488, 0.1871]])

In [29]:
x = torch.rand(5,3)

In [30]:
x[:,1]

tensor([0.8105, 0.6071, 0.8534, 0.2162, 0.0140])

In [32]:
x[2,2].item()

0.16936123371124268

In [39]:
y = x.view(-1,5)

In [40]:
x

tensor([[0.6119, 0.8105, 0.7439],
        [0.0376, 0.6071, 0.8629],
        [0.3628, 0.8534, 0.1694],
        [0.7216, 0.2162, 0.1083],
        [0.2065, 0.0140, 0.3447]])

In [42]:
y=x.T

In [43]:
y

tensor([[0.6119, 0.0376, 0.3628, 0.7216, 0.2065],
        [0.8105, 0.6071, 0.8534, 0.2162, 0.0140],
        [0.7439, 0.8629, 0.1694, 0.1083, 0.3447]])

In [45]:
a = torch.ones(5)
b  = a.numpy()

In [49]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [50]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [51]:
c = np.ones(5)
d = torch.from_numpy(c)

In [55]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y


In [57]:
u = torch.ones(5,requires_grad=True)

In [96]:
v = torch.rand(3)
t = torch.randn(3, requires_grad=True)

In [84]:
t

tensor([-1.5333, -0.8967,  0.8909], requires_grad=True)

In [85]:
m = t+2

In [86]:
n = 2*m**2

In [87]:
n

tensor([ 0.4356,  2.4345, 16.7146], grad_fn=<MulBackward0>)

In [72]:
p = n.mean()

In [74]:
p.backward()

In [77]:
print(t.grad)

None


/var/folders/jm/z3cscd5s2tl3tj1vl58b4wcw0000gn/T/ipykernel_64962/1722598881.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_52h9q6gsr9/croot/pytorch-select_1707258249748/work/build/aten/src/ATen/core/TensorBody.h:494.)
  print(n.grad)


In [88]:
v = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)


In [89]:
n.backward(v)

In [92]:
t.grad

tensor([0.1867, 4.4131, 0.0116])

In [93]:
t.requires_grad_(False)

tensor([-1.5333, -0.8967,  0.8909])

In [94]:
s = t.detach()

In [95]:
s

tensor([-1.5333, -0.8967,  0.8909])

In [97]:
with torch.no_grad():
    q = t +2 

In [98]:
q

tensor([2.8163, 2.4404, 1.5018])

In [110]:
weights = torch.ones(4, requires_grad=True)

In [111]:
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [112]:
x1 = torch.tensor(1.0)
y1 =  torch.tensor(2.0)
w1 = torch.tensor(1.0, requires_grad=True)


In [113]:
y_hat = w1*x1

In [114]:
loss = (y_hat - y1)**2

In [115]:
loss.backward()

In [116]:
w1.grad

tensor(-2.)