In [2]:
import torch
import torchvision
import numpy as np
import math
from torch.utils.data import Dataset, DataLoader

/Users/koro/miniconda3/envs/deep/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'dlopen(/Users/koro/miniconda3/envs/deep/lib/python3.11/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <CFED5F8E-EC3F-36FD-AAA3-2C6C7F8D3DD9> /Users/koro/miniconda3/envs/deep/lib/python3.11/site-packages/torchvision/image.so
  Expected in:     <E459C462-F863-3A5A-AC9F-FD77B14BE845> /Users/koro/miniconda3/envs/deep/lib/python3.11/site-packages/torch/lib/libtorch_cpu.dylib'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [3]:
class WineDataset(Dataset):
    def __init__(self) -> None:
        # super().__init__()
        xy = np.loadtxt('/Users/koro/Downloads/wine.csv', delimiter=",",dtype = np.float32, skiprows=1)
        self.x = torch.from_numpy(xy[:,1:])
        self.y = torch.from_numpy(xy[:,[0]])
        self.n_samples =xy.shape[0]
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    def __len__(self):
        return self.n_samples


In [4]:
dataset = WineDataset()
first_data = dataset[0]

In [5]:
first_data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [6]:

dataloader = DataLoader(dataset = dataset, batch_size=4,shuffle = True)

In [7]:
dataiter = iter(dataloader)
data = next(dataiter)

In [8]:
num_epochs = 10
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)

In [22]:
for epoch in range(num_epochs):
    for i, (inputs,labels) in enumerate(dataloader):
        if (i+1)%5 == 0:
            print(f"epoch {epoch +1}, step {i+1}/{n_iterations}, data {inputs.shape}, {labels.shape}")

epoch 1, step 5/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 10/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 15/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 20/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 25/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 30/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 35/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 40/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 1, step 45/45, data torch.Size([2, 13]), torch.Size([2, 1])
epoch 2, step 5/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 2, step 10/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 2, step 15/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 2, step 20/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 2, step 25/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 2, step 30/45, data torch.Size([4, 13]), torch.Size([4, 1])
epoch 2, ste

In [14]:
class WineDataset(Dataset):
    def __init__(self,transform = None):
        # super().__init__()
        xy = np.loadtxt('/Users/koro/Downloads/wine.csv', delimiter=",",dtype = np.float32, skiprows=1)
        self.x = xy[:,1:]
        self.y = xy[:,[0]]
        self.n_samples =xy.shape[0]
        self.transform = transform
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    def __len__(self):
        return self.n_samples


In [15]:

class ToTensor:
    def __call__(self,sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [16]:
dataset = WineDataset(transform=ToTensor())

In [18]:
dataset[0]

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [19]:
class multransform:
    def __init__(self,factor):
        self.factor = factor
    def __call__(self,sample):
        inputs, target = sample
        inputs *= self.factor
        return inputs,target

In [20]:
composed = torchvision.transforms.Compose([ToTensor(), multransform(2)])

In [21]:
dataset = WineDataset(composed)

In [22]:
dataset[0]

(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
         6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
         2.1300e+03]),
 tensor([1.]))